/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Configuration options passed from JavaScript to Rust.
 *
 * Each field (except `cwd`) is a JavaScript function wrapped in a `ThreadsafeFunction`.
 * These functions are called by Rust to resolve tool binary paths when needed.
 *
 * The `ThreadsafeFunction` wrapper ensures the JavaScript functions can be
 * safely called from Rust's async runtime without blocking or race conditions.
 */
export interface CliOptions {
  /** Resolver function for the lint tool (oxlint) */
  lint: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  /** Resolver function for the fmt tool (oxfmt) */
  fmt: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  /** Resolver function for the vite tool (used for build/dev) */
  vite: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  /** Resolver function for the test tool (vitest) */
  test: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  /** Resolver function for the lib tool (tsdown) */
  lib: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  /** Resolver function for the doc tool (vitepress) */
  doc: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  /** Optional working directory override */
  cwd?: string
  /** Read the vite.config.ts in the Node.js side and return the `lint` and `fmt` config JSON string back to the Rust side */
  resolveUniversalViteConfig: ((err: Error | null, arg: string) => Promise<string>)
}

/**
 * Result returned by JavaScript resolver functions.
 *
 * This structure contains the information needed to execute a tool:
 * - `bin_path`: The absolute path to the tool's binary/script
 * - `envs`: Environment variables to set when executing the tool
 */
export interface JsCommandResolvedResult {
  /** Absolute path to the tool's executable or script */
  binPath: string
  /** Environment variables to set when running the tool */
  envs: Record<string, string>
}

/**
 * Main entry point for the CLI, called from JavaScript.
 *
 * This function:
 * 1. Parses command-line arguments
 * 2. Sets up the working directory
 * 3. Creates Rust-callable wrappers for JavaScript resolver functions
 * 4. Passes control to the Rust core (`vite_task::main`)
 *
 * ## JavaScript-to-Rust Bridge
 *
 * The resolver functions are wrapped to:
 * - Call the JavaScript function asynchronously
 * - Handle errors and convert them to Rust error types
 * - Convert the JavaScript result to Rust's expected format
 *
 * ## Error Handling
 *
 * Errors from JavaScript resolvers are converted to specific error types
 * (e.g., `LintFailed`, `ViteError`) to provide better error messages.
 */
export declare function run(options: CliOptions): Promise<number>
